Change Map Position to Searched Location
dhbw-ka-pm/tinf22b6-travelInsights pull request #25
Opened 2023-06-07 06:20 UTC by LenVej

You can put the Name of a Country, City or Village into the Search Bar and the Map'll change accordingly

2023-06-07 09:05 UTC, LPkkjHD requested changes

2023-06-07 09:05 UTC, LPkkjHD commented on frontend/src/page/LeafletMap.tsx
> +  const fetchLocation = async () => {
Hier würde ich lieber Promises mit #then() und #catch() verwenden anstelle des Konglomerats an async/await mit try/catch arbeiten

2023-06-13 06:59 UTC, LenVej commented on frontend/src/page/LeafletMap.tsx
> +  const fetchLocation = async () => {
Ich habe es abgeändert. Ich hoffe du hast es so gemeint, wie ich es jetzt geändert habe.

2023-06-13 07:17 UTC, LPkkjHD commented on frontend/src/page/LeafletMap.tsx
> +  const fetchLocation = async () => {
sieht gut aus

2023-06-13 07:17 UTC, LPkkjHD approved these changes

2023-06-13 07:58 UTC, merged