eM/map marker weather to downloadable xml
dhbw-ka-pm/tinf22b6-travelInsights pull request #81
Opened 2023-07-08 16:36 UTC by Stev3eM

Die Wetterdaten werden nun richtig abgegriffen, um sie in ein XML-Format zu kompilieren und diese Datei über die Mapmarker downloaden zu können.

2023-07-10 16:21 UTC, LPkkjHD requested changes

2023-07-10 16:21 UTC, LPkkjHD commented on frontend/src/components/MapMarker.tsx
> +        </traveldestination>`;
```suggestion
        </TravelDestination>`;
```

2023-07-11 08:58 UTC, Stev3eM commented on frontend/src/components/MapMarker.tsx
> +        `<traveldestination>
Habe die Änderung vorgenommen, commited und versucht zu pullen. Pullen funktioniert aber nicht, da anscheinend schon alles up to date sei.

git pull origin eM/MapMarker_WeatherToDownloadableXML
From https://github.com/dhbw-ka-pm/tinf22b6-travelInsights
 * branch            eM/MapMarker_WeatherToDownloadableXML -> FETCH_HEAD
Already up to date.

2023-07-12 14:56 UTC, LPkkjHD approved these changes

2023-07-12 14:56 UTC, merged